export const COUNTER =  {
  INCREMENT: 'COUNTER INCREMENT',
  DECREMENT: 'COUNTER DECREMENT',
  LOADING: 'COUNTER_LOADING',
  LOADED: 'COUNTER_LOADED',
  ERROR: 'COUNTER_ERROR',
  CLEAR_ERROR: 'CLEAR_COUNTER_ERROR'
};